# Simplified per-cluster deployment for DEV
# Since each environment has its own cluster, we use a single namespace
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
  - ../../kustomize
images:
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    newTag: v0.10.1
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    newTag: v0.10.2
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/shoppingassistantservice
    newTag: v0.10.2

# Optional: Add dev-specific patches here for resource limits, replicas, etc.
# patches:
#   - target:
#       kind: Deployment
#       name: frontend
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/resources/requests/cpu
#         value: "100m"
