---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: online-boutique
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - stage: dev
          - stage: prod
  template:
    metadata:
      name: online-boutique-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-microservices:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/cyberslot/kargo-microservices.git
        targetRevision: main
        path: env/{{stage}}
      destination:
        server: https://kubernetes.default.svc
        namespace: online-boutique-{{stage}}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        automated:
          prune: true
          selfHeal: true
